#!/bin/tcsh

eos cp flatTree_ttHJetTobb_M125_13TeV_amcatnloFXFX_madspin_pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
eos cp flatTree_ttHJetToNonbb_M125_13TeV_amcatnloFXFX_madspin_pythia8_mWCutfix.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
eos cp flatTree_TTZToQQ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
eos cp flatTree_TTWJetsToQQ_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
eos cp flatTree_WWTo4Q_4f_13TeV_amcatnloFXFX_madspin_pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
eos cp flatTree_ZZTo4Q_13TeV_amcatnloFXFX_madspin_pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/

#eos cp flatTree_JetHT_Run2016B.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_JetHT_Run2016C.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_JetHT_Run2016D.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_JetHT_Run2016E.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_JetHT_Run2016F.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_JetHT_Run2016G.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_JetHT_Run2016H.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_JetHT.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_WJetsToQQ_HT180_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_DYJetsToQQ_HT180_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TTJets_TuneCUETP8M2T4_13TeV-amcatnloFXFX-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_13TeV-powheg-fsrdown-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_13TeV-powheg-fsrup-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_13TeV-powheg-isrdown-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_13TeV-powheg-isrup-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_mtop1665_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_mtop1695_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_mtop1715_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_mtop1735_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_mtop1755_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4_mtop1785_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4down_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneCUETP8M2T4up_13TeV-powheg-pythia8.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
#eos cp flatTree_TT_TuneEE5C_13TeV-powheg-herwigpp.root /eos/cms/store/cmst3/user/kkousour/ttbar/flat/
