#!/bin/tcsh
rm -rf crab_ttHJetTobb_M125_13TeV_amcatnloFXFX_madspin_pythia8_ext3
crab submit crab_ttHJetTobb_M125_13TeV_amcatnloFXFX_madspin_pythia8_ext3.py
rm -rf crab_ttHJetToNonbb_M125_13TeV_amcatnloFXFX_madspin_pythia8_mWCutfix_ext1
crab submit crab_ttHJetToNonbb_M125_13TeV_amcatnloFXFX_madspin_pythia8_mWCutfix_ext1.py
rm -rf crab_TTZToQQ_TuneCUETP8M1_13TeV-amcatnlo-pythia8
crab submit crab_TTZToQQ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.py
rm -rf crab_TTWJetsToQQ_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8
crab submit crab_TTWJetsToQQ_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.py
rm -rf crab_WZ_TuneCUETP8M1_13TeV-pythia8_ext1
crab submit crab_WZ_TuneCUETP8M1_13TeV-pythia8_ext1.py
rm -rf crab_WWTo4Q_4f_13TeV_amcatnloFXFX_madspin_pythia8
crab submit crab_WWTo4Q_4f_13TeV_amcatnloFXFX_madspin_pythia8.py
rm -rf crab_ZZTo4Q_13TeV_amcatnloFXFX_madspin_pythia8
crab submit crab_ZZTo4Q_13TeV_amcatnloFXFX_madspin_pythia8.py
